create table contrato (
    contrato_id bigint generated by default as identity primary key,
    contrato_codigo varchar(15),
    contrato_data timestamp not null,
    simulacao_codigo varchar(15) not null
)