create table contrato (
    contrato_id bigint generated by default as identity primary key,
    contrato_codigo varchar(20) unique,
    contrato_data datetime not null,
    simulacao_codigo varchar(20) not null unique
)