server:
  port: 8888
spring:
  application:
    name: 'consignado-config-server'
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/MichaelCX77/case-consignado-config