create table contrato (contrato_id bigint generated by default as identity, contrato_codigo varchar(255), contrato_data timestamp, simulacao_codigo varchar(255), primary key (contrato_id));
create table contrato (contrato_id bigint generated by default as identity, contrato_codigo varchar(255), contrato_data timestamp, simulacao_codigo varchar(255), primary key (contrato_id));
