create table cliente (
    cliente_id  bigint generated by default as identity primary key,
    cliente_cpf varchar(14) unique,
    cliente_nome varchar(255),
    cliente_correntista char(1) not null,
    cliente_segmento_tipo varchar(15),
    cliente_convenio_tipo varchar(15),
    foreign key (cliente_segmento_tipo) references segmento (segmento_tipo),
    foreign key (cliente_convenio_tipo) references convenio (convenio_tipo)
)